steps:
  - wait

  - label: ":pipeline: Generate Pipeline Steps"
    command:
      - "./.buildkite/generate-pipeline.sh > generated-pipeline.yml"
      - "buildkite-agent pipeline upload < generated-pipeline.yml"
      - "buildkite-agent artifact upload generated-pipeline.yml"
    agents:
      queue: "automation-basic-builder-fleet"
