steps:
  - wait

  - label: Build boost 1.71
    command: 
      - "git clone $BUILDKITE_REPO homebrew-eosio && cd homebrew-eosio && git checkout -f $BUILDKITE_COMMIT"
      - "brew tap eosio/eosio"
      - "cd /usr/local/Homebrew/Library/Taps/eosio/homebrew-eosio && git pull origin $BUILDKITE_BRANCH && git checkout $BUILDKITE_COMMIT"
      - "brew install --build-bottle eosio/eosio/boost@1.71"
      - "brew bottle eosio/eosio/boost@1.71"
      - "brew postinstall eosio/eosio/boost@1.71"
      - "buildkite-agent artifact upload *.tar.gz"
    plugins:
      - chef/anka#v0.5.5:
          no-volume: true
          inherit-environment-vars: true
          vm-name: "10.14.6_6C_14G_40G"
          vm-registry-tag: "clean::cicd::git-ssh::nas::brew::buildkite-agent"
          always-pull: true
          debug: true
          wait-network: true
          failover-registries:
            - 'registry_1'
            - 'registry_2'
          pre-execute-sleep: 10
      - thedyrt/skip-checkout#v0.1.1:
          cd: ~
    agents:
      queue: mac-anka-node-fleet

  - label: Build llvm 4
    command: 
      - "git clone $BUILDKITE_REPO homebrew-eosio && cd homebrew-eosio && git checkout -f $BUILDKITE_COMMIT"
      - "brew tap eosio/eosio"
      - "cd /usr/local/Homebrew/Library/Taps/eosio/homebrew-eosio && git pull origin $BUILDKITE_BRANCH && git checkout $BUILDKITE_COMMIT"
      - "brew install --build-bottle eosio/eosio/llvm@4"
      - "brew bottle eosio/eosio/llvm@4"
      - "brew postinstall eosio/eosio/llvm@4"
      - "buildkite-agent artifact upload *.tar.gz"
    plugins:
      - chef/anka#v0.5.5:
          no-volume: true
          inherit-environment-vars: true
          vm-name: "10.14.6_6C_14G_40G"
          vm-registry-tag: "clean::cicd::git-ssh::nas::brew::buildkite-agent"
          always-pull: true
          debug: true
          wait-network: true
          failover-registries:
            - 'registry_1'
            - 'registry_2'
          pre-execute-sleep: 10
      - thedyrt/skip-checkout#v0.1.1:
          cd: ~
    agents:
      queue: mac-anka-node-fleet

  - label: Build llvm 7
    command: 
      - "git clone $BUILDKITE_REPO homebrew-eosio && cd homebrew-eosio && git checkout -f $BUILDKITE_COMMIT"
      - "brew tap eosio/eosio"
      - "cd /usr/local/Homebrew/Library/Taps/eosio/homebrew-eosio && git pull origin $BUILDKITE_BRANCH && git checkout $BUILDKITE_COMMIT"
      - "brew install --build-bottle eosio/eosio/llvm@7"
      - "brew bottle eosio/eosio/llvm@7"
      - "brew postinstall eosio/eosio/llvm@7"
      - "buildkite-agent artifact upload *.tar.gz"
    plugins:
      - chef/anka#v0.5.5:
          no-volume: true
          inherit-environment-vars: true
          vm-name: "10.14.6_6C_14G_40G"
          vm-registry-tag: "clean::cicd::git-ssh::nas::brew::buildkite-agent"
          always-pull: true
          debug: true
          wait-network: true
          failover-registries:
            - 'registry_1'
            - 'registry_2'
          pre-execute-sleep: 10
      - thedyrt/skip-checkout#v0.1.1:
          cd: ~
    agents:
      queue: mac-anka-node-fleet